[FIX] l10n_ch: prevent qr-generation if draft
Steps to reproduce:
- have a Swiss configuration for qr-code
1) make sure your customer company is in Switzerland and has all the address information
2) make sure the customer set an Invoicing address in Switzerland (address + Country)
3) have set for your bank account in in Accounting/Journals/Bank: the Iban AND the QR iban
- create a sub for a Swiss client
* monthly
* confirm
- Click on create invoice

Issue:
UserError: "The following error prevented 'Swiss QR bill' QR-code to be generated though it was detected as eligible: When using a QR-IBAN as the destination account of a QR-code, the payment reference must be a QR-reference"

Cause:
We are generating the template invoice altough the invoice is in draft.
In Switzerland, for the qr-code to be valid it must have a payment reference which is only correctly generated on a confirmed invoice
Also:
For clients living in SEPA members countries, it won't work either because we are not able to change the QR mode payment to Sepa

Solution:
prevent the generation of qr-code when the invoice is in draft mode for the Swiss localization

bonus:
there won't be any error in the preview of a draft invoice in a classic Invoice flow

opw-3104890