Cherry pick of 56da3282d76dfad8c13f6b128620691355e2c65c failed
stdout:
Auto-merging addons/mail/tests/test_mail_composer.py
CONFLICT (content): Merge conflict in addons/mail/tests/test_mail_composer.py
Auto-merging addons/test_mail/tests/test_mail_composer.py
CONFLICT (content): Merge conflict in addons/test_mail/tests/test_mail_composer.py
Auto-merging addons/test_mail/tests/test_mail_gateway.py

stderr:
15:31:34.986402 git.c:455               trace: built-in: git cherry-pick 56da3282d76dfad8c13f6b128620691355e2c65c
error: could not apply 56da3282d76... [IMP] mail: add tests for private partners in composer
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: